version: "3.3"

services:
  redis:
    image: "redis:6" # Usando a imagem oficial do Redis
    container_name: redis
    ports:
      - "6379:6379" # Expondo a porta do Redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
